AWSTemplateFormationVersion: '2010-09-09'
Metadata:
  License: MIT
Description: 'This is a private S3 bucket to CloudFront distribution.'
Parameters:
  HostedZone:
    Type: String
    Description: The DNS zone to use by r53 ZoneID
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
Mappings:
  Region253WebsiteSuffix:
    us-east-1:
      Suffix: .s3-website-us-east-1.amazonaws.com
Resources:
  S3BucketForWebsiteContent:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketEncryption: BucketEncryption
      Tags: 
        - Key: "cft-template"
          Value: "blog-prod.cft.yml"
        - Key: "engineer"
          Value: "john@gatewaynode.com"
  # WebsiteCDN:
  #   Type: AWS::CloudFront::Distribution
  #   Properties:
  #     DistributionConfig:
  #       Comment: This is the CDN config
  #       Aliases:
  #         - !Join ['', [!Ref 'AWS::StackName', !Ref 'AWS::AccountId', ., !Ref 'AWS::Region',
  #           ., !Ref 'HostedZone']]
  #       Enabled: 'true'
  #       DefaultBehavior:
  #         ForwardValues:
  #           QueryString: 'true'
  #         TargetOriginId: